web/router.ex
defmodule Kraken.Router do
  use Kraken.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug :put_user_token
  end

  scope "/", Kraken do
    pipe_through [:browser, :browser_auth]

    get  "/", PageController, :index

    get  "/signup", UserController, :new
    post "/signup", UserController, :create
    get  "/login",  SessionController, :new
    post "/login",  SessionController, :create
    delete "/logout",  SessionController, :destroy

    get  "/dashboard", DashboardController, :index
    get  "/connections", ConnectionController, :index
  end

  scope "/connection", Kraken do
    pipe_through [:browser, :browser_auth]

    get "/:identity", ConnectionController, :request
    get "/:identity/callback", ConnectionController, :callback
    post "/:identity/callback", ConnectionController, :callback
  end

  defp put_user_token(conn, _) do
    current_user = Guardian.Plug.current_resource(conn)

    if current_user do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)

      conn
      |> assign(:user_id, current_user.id)
      |> assign(:user_token, token)
    else
      conn
    end
  end
end

web/views/layout_view.ex
defmodule Kraken.LayoutView do
  use Kraken.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= tag :meta, name: "id", content: assigns[:user_id] %>
    <%= tag :meta, name: "token", content: assigns[:user_token] %>

    <title>Kraken</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:700,500,400,200,100,100italic,300,300italic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
      <nav class="navbar bg-deep-purple-900 text-normal navbar-fixed-top">
    <div class="container">
        <ul class="nav navbar-nav">
          <a class="navbar-brand" href="#">Kraken</a>
          <li class="nav-item">
            <%= link "Dashboard", to: dashboard_path(@conn, :index), class: "nav-link" %>
          </li>
          <li>
            <%= link "Connections", to: connection_path(@conn, :index), class: "nav-link" %>
          </li>
        </ul>
        <ul class="nav navbar-nav pull-xs-right">
          <li>
            <%= link "Log out", to: session_path(@conn, :destroy), method: :delete, class: "nav-link" %>
          </li>
        </ul>
    </div>
      </nav>

    <div class="content-wrapper">
      <div class="container">
        <%= get_flash(@conn, :info) %>
        <%= get_flash(@conn, :error) %>

        <%# <%= render "navigation.html", current_user: @current_user, conn: @conn %1> %>

        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/chromeless.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Kraken</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:700,500,400,200,100,100italic,300,300italic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <div class="content-wrapper">
      <div class="container-fluid">
        <div class="chromeless-wrapper">
          <%= show_flash(@conn) %>
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>